title: Image

fields:

  title:
    label: Alt-Text
    type: text
    width: 1/2
    placeholder: '{{ file.filename }}'

  credits:
    label: Credits
    type: text
    before: '©'
    translate: false
    width: 1/2

  description:
    type: text
