title: File

fields:

  alt:
    label: field.blocks.image.alt
    type: text
    placeholder: '{{ file.parent.title }} {{ file.filename }}'
    icon: title

  caption:
    label: field.blocks.image.caption
    type: writer
    icon: text
    inline: true