title: Image

fields:

  title:
    label: Title
    type: text
    width: 1/2
    placeholder: '{{ file.filename }}'

  credits:
    label: Credits
    type: text
    before: '©'
    translate: false
    width: 1/2

  description:
    extends: fields/description
    label: Image caption
    maxlength: 300
