columns:
  - width: 1/2
    sections:

      fields1:
        type: fields
        fields:

          tags: fields/tags

          description:
            extends: fields/description
            maxlength: 200

  - width: 1/2
    sections:

      fields2:
        type: fields
        fields:

          ogimage:
            extends: fields/image
            label: OG Image
            empty: No image uploaded yet
