icon: url
columns:
  - width: 1/2
    sections:

      fields1:
        type: fields
        fields:

          tags:
            extends: fields/tags
            label: Meta keywords

          description:
            extends: fields/textarea
            label: Meta description
            maxlength: 200

  - width: 1/2
    sections:

      fields2:
        type: fields
        fields:

          ogimage:
            extends: fields/image
            label: Social Media preview image
