title: Default page
icon: page

tabs:

  page:
    icon: page
    columns:

      - width: 2/3
        fields:

          blocks:
            extends: fields/blocks

      - width: 1/3
        sections:
          
          pages:
            extends: sections/pages

          files:
            extends: sections/files

  meta: tabs/meta/page