title: Site

tabs:

  index:
    label: Index
    icon: dashboard

    columns:

      - width: 1/2
        sections:

          pages:
            extends: sections/pages

  settings:
    icon: cog
    columns:
      - width: 1/2
        fields:

          menu:
            extends: fields/pages
            label: Menu
          
          menuFooter:
            extends: fields/pages
            label: Footer-Menu

      - width: 1/2
        fields:

          contact:
            type: object
            fields:

              title:
                type: text
                label: Legal name
              address:
                type: writer
                inline: true
              zip:
                type: text
                width: 1/3
              city:
                type: text
                width: 2/3
              country:
                type: text
              email:
                type: email
              phone:
                type: tel

          links:
            extends: fields/links

  meta: tabs/meta/site
  help: tabs/help
