title: Site

tabs:

  index:
    label: Index

    columns:

      - width: 1/2
        sections:

          listed:
            extends: sections/pages

      - width: 1/2
        sections:

          unlisted:
            extends: sections/pages
            templates:
              - default
              - home
              - about
              - imprint

  meta: tabs/meta
